# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
apt-get update
apt-get install -y curl
curl https://get.docker.io/ubuntu/ | sh
usermod -aG docker vagrant
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  for i in 49000..49900
    config.vm.network "forwarded_port", guest: i, host: i
  end
  config.vm.provision "shell", inline: $script
end
